---
# defaults file for deploy_student_container

MY_NAME: "Firstname LASTNAME"

SMTP_USERNAME: mail@mail.com
SMTP_PASSWORD: "strongpassword"

OBJECT: "Credential for VM Pentest"

BODY: |
  Bonjour {{ item.firstname }},

  Voici vos identifiants de connexion personnels pour accéder à la machine virtuelle :
    - Nom d'utilisateur : {{ item.name }}
    - Mot de passe : {{ item.pass }}
    - Port SSH : {{ item.port }}

  Je vous recommande de ne rien partager avec qui que ce soit.
  Si vous rencontrez des difficultés pour vous connecter, n'hésitez pas à me contacter directement à l'adresse suivante : {{ SMTP_USERNAME }}.
  
  Cordialement,
  {{ MY_NAME }}

STUDENT_USER:
  - { firstname: Anakin, lastname: SKYWALKER, name: user1, pass: Pa$$w0rd1, port: 9001, email: mail@mail.com }
  - { firstname: Jason,  lastname: STATAM,    name: user2, pass: Pa$$w0rd2, port: 9002, email: mail@mail.com }
  - { firstname: Napo,   lastname: LEON,      name: user3, pass: Pa$$w0rd3, port: 9003, email: mail@mail.com }
